# release CI for FreeBSD
compute_engine_instance:
  image_project: freebsd-org-cloud-dev
  image: family/freebsd-13-1
  platform: freebsd
  disk: 100 # Gb

build_task:
  timeout_in: 120m
  only_if: $CIRRUS_TAG != ''
  env:
    AWS_ACCESS_KEY_ID: ENCRYPTED[24aa29bf4a2dd5f04f60c5d64dc24f32809842f5abc4a1a5c364a2904c47dd975b6b4dbb139b3a4aa2944b61188ed6b3]
    AWS_SECRET_ACCESS_KEY: ENCRYPTED[d7873f7283dfbb1319446580109fd85d932d1f568955444305c30805ee5cbd793b641a415713f49d75110ea22bb7f4dd]
    S3_HOST: ENCRYPTED[ddf64487d34b91080cfb0f207f9749c7d786424fcee3a3143ebee270afa86371656659e94842e8a7bb0b0efbefc12d8c]
    TARBALL_EXT: "tar.xz"
    ARCH: 64
    ARTIFACT: "x86_64-freebsd"
    DISTRO: "na"
    RUNNER_OS: "FreeBSD"
    ADD_CABAL_ARGS: "--enable-split-sections"
    GITHUB_WORKSPACE: ${CIRRUS_WORKING_DIR}
    CABAL_CACHE_NONFATAL: "yes"
  matrix:
    - name: build-ghc-9.2.8
      env:
        GHC_VERSION: 9.2.8
    - name: build-ghc-9.4.8
      env:
        GHC_VERSION: 9.4.8
    - name: build-ghc-9.6.4
      env:
        GHC_VERSION: 9.6.4
    - name: build-ghc-9.8.1
      env:
        GHC_VERSION: 9.8.1
  install_script: pkg install -y hs-cabal-install git bash misc/compat10x misc/compat11x misc/compat12x gmake patchelf tree gmp libiconv
  script:
    - tzsetup Etc/GMT
    - adjkerntz -a
    - bash .github/scripts/build.sh
    - tar caf out.tar.xz out/ store/
  binaries_artifacts:
    path: "out.tar.xz"


bindist_task:
  name: bindist
  depends_on:
    - build-ghc-9.2.8
    - build-ghc-9.4.8
    - build-ghc-9.6.4
    - build-ghc-9.8.1
  timeout_in: 120m
  only_if: $CIRRUS_TAG != ''
  env:
    TARBALL_EXT: "tar.xz"
    ARCH: 64
    ARTIFACT: "x86_64-freebsd"
    DISTRO: "na"
    RUNNER_OS: "FreeBSD"
    GITHUB_WORKSPACE: ${CIRRUS_WORKING_DIR}
  install_script: pkg install -y hs-cabal-install git bash misc/compat10x misc/compat11x misc/compat12x gmake patchelf tree gmp libiconv unzip
  script:
    - tzsetup Etc/GMT
    - adjkerntz -a

    - curl -o binaries-9.2.8.tar.xz -L https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/build-ghc-9.2.8/binaries/out.tar.xz
    - tar xvf binaries-9.2.8.tar.xz
    - rm -f binaries-9.2.8.tar.xz

    - curl -o binaries-9.4.8.tar.xz -L https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/build-ghc-9.4.8/binaries/out.tar.xz
    - tar xvf binaries-9.4.8.tar.xz
    - rm -f binaries-9.4.8.tar.xz

    - curl -o binaries-9.6.4.tar.xz -L https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/build-ghc-9.6.4/binaries/out.tar.xz
    - tar xvf binaries-9.6.4.tar.xz
    - rm -f binaries-9.6.4.tar.xz

    - curl -o binaries-9.8.1.tar.xz -L https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/build-ghc-9.8.1/binaries/out.tar.xz
    - tar xvf binaries-9.8.1.tar.xz
    - rm -f binaries-9.8.1.tar.xz

    - bash .github/scripts/bindist.sh
  bindist_artifacts:
    path: "./out/*.tar.xz"

test_task:
  name: test
  depends_on:
    - bindist
  timeout_in: 120m
  only_if: $CIRRUS_TAG != ''
  env:
    TARBALL_EXT: "tar.xz"
    ARCH: 64
    ARTIFACT: "x86_64-freebsd"
    DISTRO: "na"
    RUNNER_OS: "FreeBSD"
    GITHUB_WORKSPACE: ${CIRRUS_WORKING_DIR}
  install_script: pkg install -y hs-cabal-install git bash misc/compat10x misc/compat11x misc/compat12x gmake patchelf tree gmp libiconv unzip
  script:
    - tzsetup Etc/GMT
    - adjkerntz -a

    - curl -O -L https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}/bindist/bindist.zip
    - unzip bindist.zip

    - bash .github/scripts/test.sh

